### ISSUE TITLE
Axios error?

### ISSUE THREAD

**Issue by choccy** [abskmj/gulel#2]
When I start my application on my VPS, I get this:

```
Gulel is listening at http://localhost:5000
Gulel is listening for Twitch calls
(node:32550) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (/home/choccy/cirLive/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/choccy/cirLive/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/choccy/cirLive/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32550) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:32550) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by choccy** [comment]
Also how do you set the hostname if ngrok is disabled?

**Comment by abskmj** [comment]
have you configured twitch access token and client id? Misconfiguration could result in the 401 error. 

```js
{
  twitch: {
    accessToken: '<access token>',
    clientId: '<client id>'
  }
}
```

**Comment by abskmj** [comment]
Currently, there is no way to set the hostname when ngrok is disabled. I will add a way in a couple of days.
